Fixed: printinfo's 'histogram' output
apache/accumulo pull request #2220
Opened 2021-08-03 12:44 UTC by Shivakumar-SG

fixes issue #2217.
Let me know if there should be any changes.

2021-08-03 13:51 UTC, Manno15 commented
@Shivakumar-SG It looks like the build failed due to not being formatted correctly. You can run something like `mvn package -DskipTests` at the root of the project and it will apply the proper formatting for you. Include those changes into a new commit for this PR and the build should pass from there.

2021-08-03 18:33 UTC, Shivakumar-SG commented
I have been trying from past few hours to run `mvn package -DskipTests`, but its throwing me many errors and I couldn't fix them. What would you want me to do?

2021-08-03 18:44 UTC, DomGarguilo commented
@Shivakumar-SG what errors are being thrown?

2021-08-03 18:45 UTC, DomGarguilo commented
@Shivakumar-SG what errors are being thrown?

2021-08-03 18:47 UTC, Shivakumar-SG commented
A whole lot many actually :(

2021-08-03 18:51 UTC, Shivakumar-SG commented
if the build failed because of just the formatting, it would be great if someone could help me with the formatted code of my version

2021-08-03 18:52 UTC, DomGarguilo commented
> if the build failed because of just the formatting, it would be great if someone could help me with the formatted code of my version

Sure, I can make a PR to your branch with the formatting changes.

2021-08-03 18:55 UTC, Shivakumar-SG commented
@DomGarguilo That would be great! Thank you so much

2021-08-03 19:11 UTC, EdColeman commented
Can you provide more information?

- What platform are you running on?
- What command are you running?
- What is the first or  first few errors that you are getting?

You can do the same build as the verification checks, but skipping all of the tests by running:

`mvn package javadoc:jar -Psec-bugs -DskipITs=true -DskipTests=true`

The javadoc and sec-bugs will add to the build time, but running those before submitting the PR can highlight issues that will fail the automatic build.  This should also format the files to the community standards.

More information on building is at (Building Accumulo](https://accumulo.apache.org/contributor/building)

2021-08-03 19:40 UTC, Manno15 commented
It looks like you are missing the import for 'bigNumberForSize()' which is NumUtil.

2021-08-03 19:43 UTC, EdColeman commented
It also looks like an extra file (.DS_Store) was pushed along with you commit - that file should not be included.

2021-08-03 19:49 UTC, Manno15 commented on core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
> +            bigNumberForSize(Double.valueOf(Math.pow(10, i)).longValue()), countBuckets[i],
```suggestion
            NumUtil.bigNumberForSize(Double.valueOf(Math.pow(10, i)).longValue()), countBuckets[i],
```

2021-08-03 19:49 UTC, DomGarguilo commented
It looks like with these changes the output is something like:
![Screenshot from 2021-08-03 15-48-14](https://user-images.githubusercontent.com/47725857/128076980-c94ad179-cfef-41d1-9993-580689abb517.png)

Is this what we are looking for?

2021-08-03 19:52 UTC, Shivakumar-SG commented
> It looks like you are missing the import for `bigNumberForSize()` which is `import org.apache.accumulo.core.util.NumUtil`

Initially, I did import initially and when the command `mvn package -DskipTests` is run, it takes it out.

2021-08-03 19:55 UTC, Manno15 commented
> Initially, I did import and when the command mvn package -DskipTests is run, it takes it out.

That is most likely due to the import being unused since you weren't calling the function correctly (as suggested above). One of the format rules removes all unused imports.

2021-08-03 20:01 UTC, Manno15 commented
> Is this what we are looking for?

That output looks good to me.

2021-08-03 20:32 UTC, Manno15 requested changes
`.DS_Store` binary file should be removed from this pull request before this can be approved.

2021-08-03 20:32 UTC, Manno15 commented on core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
> +            sizeBuckets[i] * 100. / totalSize));
```suggestion
        System.out.println("%s%11s : %10d %6.2f%%", indent,
            NumUtil.bigNumberForSize(Double.valueOf(Math.pow(10, i)).longValue()), countBuckets[i],
            sizeBuckets[i] * 100. / totalSize);
```
Based from my testing, the String.format isn't necessary.

2021-08-03 20:48 UTC, EdColeman commented
For discussion on output format - it looks like there are some options - using powers pr 10 or 2.  To produce a sample:

```
    for (int x = 1; x < 15; x++) {
      System.out.println(
          String.format("%s%11s", " ", NumUtil.bigNumberForQuantity((long) Math.pow(10, x))));
    } 
    System.out.println("---");
    for (int x = 1; x < 16; x++) {
      System.out.println(
          String.format("%s%11s", " ", NumUtil.bigNumberForSize((long) Math.pow(16, x))));
    }
```
This produces:
```
          10
         100
       1.00K
      10.00K
     100.00K
       1.00M
      10.00M
     100.00M
       1.00B
      10.00B
     100.00B
       1.00T
      10.00T
     100.00T
---
          16
         256
       4.00K
      64.00K
       1.00M
      16.00M
     256.00M
       4.00G
      64.00G
       1.00T
      16.00T
```
Having even numbers seems more pleasing (to me) base 2 or 10 work, but being the buckets are calculated using 100, bigNumberForQuantity might be easier to implement with this PR.  Being this is size, an argument for the second option is valid, but might require additional work to calculate the buckets correctly.

2021-08-03 20:50 UTC, Manno15 commented on core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
> +        System.out.println("%s%11s : %10d %6.2f%%", indent,
```suggestion
        System.out.printf("%s%11s : %10d %6.2f%%", indent,
```

That is my mistake, I forgot to add this change.

2021-08-03 21:15 UTC, Manno15 commented
> Having even numbers seems more pleasing (to me) base 2 or 10 work, but being the buckets are calculated using 100, bigNumberForQuantity might be easier to implement with this PR. Being this is size, an argument for the second option is valid, but might require additional work to calculate the buckets correctly.

Good point, I concur that Quantity might be preferable since it lines up closer to the original output.

2021-08-04 13:34 UTC, Manno15 commented
@Shivakumar-SG What are your thoughts on the conversation above? 

> Having even numbers seems more pleasing (to me) base 2 or 10 work, but being the buckets are calculated using 100, bigNumberForQuantity might be easier to implement with this PR. Being this is size, an argument for the second option is valid, but might require additional work to calculate the buckets correctly.

2021-08-04 14:17 UTC, Shivakumar-SG commented
> @Shivakumar-SG What are your thoughts on the conversation above?
> 
> > Having even numbers seems more pleasing (to me) base 2 or 10 work, but being the buckets are calculated using 100, bigNumberForQuantity might be easier to implement with this PR. Being this is size, an argument for the second option is valid, but might require additional work to calculate the buckets correctly.

@Manno15 Thank you for showing your interest in my views but I'm just a student who is still learning and knows pretty much nothing about this repo. So I don't think so that I'm fit to share my views on such a big project.
I will just do what you tell me to do sir!

2021-08-04 16:07 UTC, Manno15 commented on core/src/main/java/org/apache/accumulo/core/file/rfile/PrintInfo.java
> +            sizeBuckets[i] * 100. / totalSize);
```suggestion
        System.out.println(String.format("%s%11s : %10d %6.2f%%", indent,
            NumUtil.bigNumberForQuantity((long) Math.pow(10, i)), countBuckets[i],
            sizeBuckets[i] * 100. / totalSize));
```

2021-08-04 16:47 UTC, Manno15 approved these changes
Looks great.

2021-08-04 17:03 UTC, DomGarguilo approved these changes
LGTM. Output is as follows and looks good:
```
Up to size      Count      %-age
         10 :     500212   3.04%
        100 :   13459310  96.96%
      1.00K :          0   0.00%
     10.00K :          0   0.00%
    100.00K :          0   0.00%
      1.00M :          0   0.00%
     10.00M :          0   0.00%
    100.00M :          0   0.00%
      1.00B :          0   0.00%
     10.00B :          0   0.00%
```

2021-08-04 17:04 UTC, EdColeman approved these changes

2021-08-04 17:21 UTC, merged

2021-08-04 17:21 UTC, Manno15 commented
Thanks for the contribution @Shivakumar-SG and welcome to the Apache Accumulo community! If you would like to be listed as a contributor on Accumulo's people page please make a website PR for people.md. https://github.com/apache/accumulo-website/edit/main/pages/people.md

If you intend to make more contributions, please consider subscribing to the dev list and introducing yourself. Also, you can use the dev list or slack to reach out if you have questions about anything. https://accumulo.apache.org/contact-us/

2021-08-04 17:28 UTC, Shivakumar-SG commented
I will consider your options. Thank you so much for letting me do this.

2021-08-04 17:34 UTC, EdColeman commented
Thanks for the contribution Shivakumar-SG and welcome to the Apache Accumulo community. If you would like to be listed as a contributor on Accumulo's people page please make a website PR for people.md. https://github.com/apache/accumulo-website/edit/main/pages/people.md by:
 -  adding your name (in alphabetical order) to the contributor's list.
 -  reference the PR number (#2220)
If you intend to make more contributions, please consider subscribing to the dev list and introducing yourself. Also, you can use the dev list or slack to reach out if you have questions about anything. https://accumulo.apache.org/contact-us/

2021-08-04 18:06 UTC, Shivakumar-SG commented
Thank you for helping me out in this @EdColeman and @DomGarguilo :)