Modify snapshot synchronization
apache/accumulo pull request #2769
Opened 2022-06-10 23:10 UTC by EdColeman

Modify the synchronization of configurations cached in the ServerConfigurationFactory with ZooKeeper.

The previous implementation leveraged the caffeine cache refresh after write capability - however, the secondary caching of configurations in the SeverConfigurationFactory makes that capability less effective. Because the secondary cache and the data versions use the secondary cache, the prop cache implementation is read less frequently. The use of data versions is an optimization for iterators that avoids any overhead from reading the entire property payload.

These changes provide the following benefits over the original implementation:
- deletions are detected and eliminate the persistent caching of configurations.
- detected changes are propagated to the prop store.
- uses lighter weight getStatus calls.
- provides jitter between calls and staggered invocations to reduce ZooKeeper load

2022-06-11 06:05 UTC, ctubbsii requested changes
I like the approach for keeping ServerConfigurationFactory up-to-date after tables/namespaces are deleted, but I'm not sure about moving the snapshot refresh stuff into it, or the other changes. Can we just handle the table/namespace deletions and update ServerConfigurationFactory first, and then evaluate the other changes in a subsequent PR?

2022-06-11 06:05 UTC, ctubbsii commented on server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
> +        tableConfigs.remove(((TablePropKey) propStoreKey).getId());
This is removed twice. I think the intent was:

```suggestion
        tableConfigs.remove(((TablePropKey) propStoreKey).getId());
        tableParentConfigs.remove(((TablePropKey) propStoreKey).getId());
```

2022-06-11 13:02 UTC, EdColeman commented on server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
> +      // simplify testing - only create refresh thread when operating in a context with thread pool
When mocking it is null - otherwise the pool needs to added to the mock and it seemed to cause a circular dependency in the mock.

2022-06-14 01:17 UTC, ctubbsii commented
Some of this was moved into #2773. This can be rebased after that is merged.

2022-06-15 12:53 UTC, EdColeman commented
This PR has been superseded with separate PRs.  This has been partially completed with PR #2773 to add delete watcher too ServerConfigurationFactory.  PR #2778 will resolve the remaining data version sync functionality.

2022-06-15 12:53 UTC, closed without merging