Source accumulo-env.sh from accumulo-cluster script
apache/accumulo pull request #2894
Opened 2022-08-24 13:11 UTC by dlmarion

Users can set env vars to control the number of tservers/sservers
started per host. accumulo-env.sh is sourced from other scripts in
bin, except accumulo-cluster. This commit adds the variables to
accumulo-env.sh (with default of 1) and modifies accumulo-cluster
to source the file like the other scripts in bin do.

2022-08-27 19:07 UTC, Manno15 approved these changes
Changes look fine on their own. Was there a specific issue that prompted this change? My one concern would be the interaction with the `NUM_TSERVERS` export in `fluo-uno/conf/uno.conf` if one was using fluo-uno to setup the cluster. Which would take precedent. My brief testing points to your chance to accumlo-env takes precedent which may cause some issues for some people.

2022-08-27 19:14 UTC, Manno15 requested changes
On some further testing, I have noticed this breaks fluo-uno. At least with the monitor as it no longer functions with these changes.

2022-08-27 20:42 UTC, dlmarion commented
I'm not really concerned about breaking the fluo-uno build if there is a way to fix it. Downstream projects will have to be updated for changes in Accumulo.

2022-08-29 10:47 UTC, dlmarion commented
@Manno15  - Is fluo-uno easily fixed? Is the only issue NUM_TSERVERS export in fluo-uno/conf/uno.conf?

2022-08-29 10:51 UTC, Manno15 commented
@dlmarion, I would need to do more testing to be sure that it was the only
issue. (unsure on how the export SServer changes anything within fluo-uno)
but if it is the only issue then it should be easy to fix.

On Mon, Aug 29, 2022 at 6:47 AM Dave Marion ***@***.***>
wrote:

> @Manno15 <https://github.com/Manno15> - Is fluo-uno easily fixed? Is the
> only issue NUM_TSERVERS export in fluo-uno/conf/uno.conf?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/accumulo/pull/2894#issuecomment-1230116806>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHASSV534OL7UCHY6CAEOCLV3SIMXANCNFSM57PI52RQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-29 15:34 UTC, dlmarion commented
It looks like I can change `NUM_TSERVERS=1` to `export NUM_TSERVERS=${NUM_TSERVERS:=1}`. If NUM_TSERVERS is already defined in the environment, then it will use that, else default to 1.

2022-08-29 15:49 UTC, EdColeman approved these changes

2022-08-29 17:28 UTC, DomGarguilo commented
> Is the only issue NUM_TSERVERS export in fluo-uno/conf/uno.conf?

From my testing, the changes from this PR breaks at least the monitor when setting things up via fluo-uno. Two things to note:
1. When specifying number of tservers in the uno.conf, it looks like that takes precedent over the changes made here
2. When commenting out the changes in `/bin/accumulo-cluster` the monitor seems to work fine once again when running with uno

2022-08-29 17:34 UTC, dlmarion commented
> When specifying number of tservers in the uno.conf, it looks like that takes precedent over the changes made here

Yes, that was intended with the changes in 0adb798

> When commenting out the changes in /bin/accumulo-cluster the monitor seems to work fine once again when running with uno

Is there a stacktrace in the monitor log? Is there an error?

2022-08-29 18:02 UTC, DomGarguilo commented
> Is there a stacktrace in the monitor log? Is there an error?

```
Exception in thread "monitor" java.lang.NoSuchMethodError: 'jakarta.servlet.SessionCookieConfig org.eclipse.jetty.server.session.SessionHandler.getSessionCookieConfig()'
	at org.apache.accumulo.monitor.EmbeddedWebServer.<init>(EmbeddedWebServer.java:59)
	at org.apache.accumulo.monitor.Monitor.run(Monitor.java:452)
	at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

2022-08-29 18:04 UTC, dlmarion commented
Yeah, I just built this branch and deployed it. Same error:
```
2022-08-29T18:01:21,195 [util.log] INFO : Logging initialized @7835ms to org.eclipse.jetty.util.log.Slf4jLog
Exception in thread "monitor" java.lang.NoSuchMethodError: 'jakarta.servlet.SessionCookieConfig org.eclipse.jetty.server.session.SessionHandler.getSessionCookieConfig()'
        at org.apache.accumulo.monitor.EmbeddedWebServer.<init>(EmbeddedWebServer.java:59)
        at org.apache.accumulo.monitor.Monitor.run(Monitor.java:452)
        at org.apache.accumulo.core.trace.TraceWrappedRunnable.run(TraceWrappedRunnable.java:52)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

I ran into this error recently when testing Accumulo w/ k8s. It's a classpath issue where the Jetty jar from the Hadoop distro is being picked up first.

2022-08-29 18:37 UTC, dlmarion commented
So, when using `accumulo-cluster` on `localhost`, `accumulo-env.sh` ends up getting called twice because we don't `ssh` to `localhost`. I'm not quite sure why the classpath being duplicated causes this issue.

2022-08-29 18:46 UTC, keith-turner commented
Could the desired num tservers and sservers per host be placed in the `cluster.yaml` file instead of `accumulo-env.sh`?  Not completely sure how this would be done, so not sure if its possible.  If this could be done it then there is one file that a user needs to modify to change the behavior of the accumulo-cluster script instead of two.

2022-08-29 18:51 UTC, dlmarion commented
> Could the desired num tservers and sservers per host be placed in the cluster.yaml

That would cause an issue with fluo-uno. I have it working locally, about to push an update in a few mins

2022-08-29 21:55 UTC, keith-turner commented
> That would cause an issue with fluo-uno. 

What problem would it cause?

2022-08-30 14:04 UTC, dlmarion commented
> Could the desired num tservers and sservers per host be placed in the cluster.yaml

So, this might be possible given that the cluster.yaml file is parsed and then the output of that is sourced by the `accumulo-cluster` script. I could include the following in the output:

```
export NUM_TSERVERS=${NUM_TSERVERS:=1}
export NUM_SSERVERS=${NUM_SSERVERS:=1}
```

With this approach, `accmulo-cluster` would not need to source `accumulo-env.sh`. I will put up a different PR for evaluation and close this one if it's accepted.

2022-08-30 16:05 UTC, dlmarion commented
See #2903 for alternate implementation

2022-08-31 18:17 UTC, closed without merging