refactor fates storage layer
apache/accumulo pull request #4017
Opened 2023-12-04 20:04 UTC by keith-turner

Refactored the storage layer of FATE to return an object when reserving a fate transaction.  This object allows mutating the storage related to that FATE transaction.  This replaces methods where the fate transaction id had to to always be passed.

These changes are a subset of the changes in #3964, but only focusing on the storage layer refactoring and nothing else.

2023-12-05 23:38 UTC, cshannon requested changes
The overall structure of the changes look good to me but I tried running the FateIT test and it is failing for me for multiple of the tests so something doesn't seem quite right.


```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.accumulo.test.fate.zookeeper.FateIT
[ERROR] Tests run: 4, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 20.61 s <<< FAILURE! -- in org.apache.accumulo.test.fate.zookeeper.FateIT
[ERROR] org.apache.accumulo.test.fate.zookeeper.FateIT.testCancelWhileSubmittedAndRunning -- Time elapsed: 3.695 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertFalse.failNotFalse(AssertFalse.java:63)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:36)
	at org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:31)
	at org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:228)
	at org.apache.accumulo.test.fate.zookeeper.FateIT.testCancelWhileSubmittedAndRunning(FateIT.java:279)
...

[ERROR] org.apache.accumulo.test.fate.zookeeper.FateIT.testCancelWhileNew -- Time elapsed: 3.038 s <<< ERROR!
java.lang.IllegalStateException: Can not delete in progress transaction FATE[389879b65476f988]
	at org.apache.accumulo.core.fate.Fate.delete(Fate.java:356)
	at org.apache.accumulo.test.fate.zookeeper.FateIT.testCancelWhileNew(FateIT.java:241)
...

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FateIT.testCancelWhileSubmittedAndRunning:279 expected: <false> but was: <true>
[ERROR] Errors: 
[ERROR]   FateIT.testCancelWhileNew:241 » IllegalState Can not delete in progress transaction FATE[389879b65476f988]
[INFO] 
[ERROR] Tests run: 4, Failures: 1, Errors: 1, Skipped: 0
```

2023-12-05 23:57 UTC, cshannon approved these changes

2023-12-06 14:19 UTC, keith-turner commented
> @keith-turner - The test failures appear to be race condition related. I took a shot at fixing the tests and pushed a commit up that fixes it. Feel free to revert it or change it if you think it isn't correct of course.

Those changes look good. Thanks for the fix.   Thinking  that is a pre-existing bug in the test, may be worthwhile back-porting just the test changes.

2023-12-06 14:19 UTC, merged

2023-12-06 15:39 UTC, keith-turner commented
@cshannon I backported the FateIT changes in #4029